{% set name = "napari-input-visualizer" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-input-visualizer-{{ version }}.tar.gz
  sha256: 7c50d61a0d593164c06e8c369a960fb6b0744b24173e4bc78234fab0c4d42182

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - imageio-ffmpeg
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_input_visualizer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bauerdavid/napari-input-visualizer
  summary: Visualize keyboard and mouse button presses
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bauerdavid
    - goanpeca
    - jaimergp
